### Test GET request
GET http://localhost:8000/api/items
Accept: application/json

### Test POST request
POST http://127.0.0.1:8000/api/auth/login/
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "Test@123"
}

### 2️⃣ Get Filtered Doe Data (Logged-in User Required)
POST http://127.0.0.1:8000/api/filter-doe/?Tool_Diameter=80
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQxMTA2NTQ4LCJpYXQiOjE3NDExMDYyNDgsImp0aSI6IjU4NTFhMGI1ZmM3YTQwMGViMjVkMTJmYjljYWY3OGMxIiwidXNlcl9pZCI6M30.JOsNreGZsAgoTI5HfSF8HYnqbQ8V5yRIQYdpYwFO0SQ

### Test PUT request
PUT http://localhost:8000/api/items/1
Content-Type: application/json

{
  "name": "Updated Item",
  "description": "This is an updated test item",
  "price": 12.99
}

### Test DELETE request
DELETE http://localhost:8000/api/items/1
