### Test GET request
GET http://localhost:8000/api/items
Accept: application/json

### Test POST request
POST http://127.0.0.1:8000/api/auth/login/
Content-Type: application/json

{
    "email": "4kjessy@gmail.com",
    "password": "jessy415"
}

### Test PUT request
PUT http://localhost:8000/api/items/1
Content-Type: application/json

{
  "name": "Updated Item",
  "description": "This is an updated test item",
  "price": 12.99
}

### Test DELETE request
DELETE http://localhost:8000/api/items/1
