services:
  - type: web
    name: doeproject
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn doeproject.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: "False"