# Generated by Django 5.1.6 on 2025-03-02 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_customusermanager_remove_customuser_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
