# Generated by Django 5.1.6 on 2025-03-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('searchdoe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoeData',
            fields=[
                ('DOE_Serial_Number', models.AutoField(primary_key=True, serialize=False)),
                ('Tool_Diameter', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'doe_data',
                'managed': False,
            },
        ),
    ]
